### ISSUE TITLE
Welcome to Study Groups!

### ISSUE THREAD

**Issue by auremoser** [FoxIOT/studyGroup#9]
Hi @dvigneshwer!
Thanks for your interest in the [Mozilla Science Lab](https://mozillascience.org/), it's great to read you're building a [Study Group](https://github.com/mozillascience/studygroup).

My name is [Aurelia](https://mozillascience.org/u/auremoser) and I work at the Mozilla Science Lab, a group building projects/programs globally to support open research and citizen science, including the Study Groups project. I know we've chatted in the community chat channel and over email, but I just wanted to introduce myself as a resource, and answer any questions you might have.

Feel free to:
- search for ideas in [the handbook](http://mozillascience.github.io/studyGroupHandbook/)
- build out [a site for your Study Group](https://github.com/mozillascience/studyGroup) and cull from our [library of lessons](https://github.com/mozillascience/studyGroupLessons) for early sessions
- join our monthly study group call (first Fridays, 11AM EST), [subscribe to our mailing list to be notified of those calls](https://mail.mozilla.org/listinfo/msl-study-groups)
- follow our #mozstudy hashtag on twitter, or [our list](https://twitter.com/MozillaScience/lists/mozstudy), ping [@auremoser](https://twitter.com/MozillaScience) to be added

**Join us on our next Study Group Learning call, Friday October 7th, 11am EST: https://public.etherpad-mozilla.org/p/mozilla-studygroup-leads-october-2016**.

Email me at [aurelia@mozillafoundation.org](mailto:aurelia@mozillafoundation.org) with questions, I would love to learn about your lessons, challenges, topic of interest, and events. 

Thanks for reading!

Aurelia
Mozilla Science Lab
[@MozillaScience](https://twitter.com/MozillaScience)

**Comment by paarttipaabhalaji** [comment]
Sure Aurelia.....

Thank you

**Comment by dvigneshwer** [comment]
@auremoser you have been a very great source of support through out the on boarding process, thank you very much for helping us out.

We are very excited about the study group in our region and plan to make most out of it.

**Comment by auremoser** [comment]
👍  aww, thank you! glad to read that. I'll send you more updates soon on the onboarding materials we are developing!

**Comment by Yadhukrishnanp** [comment]
If this community is still active please let me know.

**Comment by daminibhattacharya** [comment]
Hello. I don't think anyone else is here.       
  
  
  
  
  

  
  
>

**Comment by dvigneshwer** [comment]
Yes.

Feel free to join the [telegram group](https://t.me/foxIoTstudygroup)

**Comment by Yadhukrishnanp** [comment]
I have joined the group today. Thank you

**Comment by daminibhattacharya** [comment]
What are you studying ?       
  
  
  
  
  

  
  
>

**Comment by Yadhukrishnanp** [comment]
I am from kerala and currently doing my btech in biomedical engineering. I
have completed 3 year diploma in medical electronics.I have attended​
couple of IOT internships, so I would like to study much more about IOT and
its markets in India.

**Comment by daminibhattacharya** [comment]
Where did you do your internship ?    
  
  
  
  
  

  
  
>

**Comment by Yadhukrishnanp** [comment]
It was internship conducted by Expertshub( industry skill development
center) Bangalore at JSS Academy for technical education.

**Comment by daminibhattacharya** [comment]
Ohh alright.    Those things costs you money?       
  
  
  
  
  

  
  
>

**Comment by Yadhukrishnanp** [comment]
Yes obviously. It was a 7 day internship. People who work in several IOT
Companies took interactive sessions. Mostly raspberry pi and adruino
hardware was used.

**Comment by daminibhattacharya** [comment]
Wow sounds so cool. I will be going for such internships in December       
  
  
  
  
  

  
  
>

**Comment by Yadhukrishnanp** [comment]
That's great. What do you do currently? student?

**Comment by daminibhattacharya** [comment]
Yeah.    Computer science engg. Going to step in final year.       
  
  
  
  
  

  
  
>

**Comment by Yadhukrishnanp** [comment]
Me too. Stepping to final year. I guess IOT is your one of your passions.

**Comment by daminibhattacharya** [comment]
One among many.    I thought this was a study group too but looks like its just me  &  you. 🙃    
  
  
  
  
  

  
  
>

**Comment by Yadhukrishnanp** [comment]
yea i did not find anyone active in this stud group.are you there in the telegram study group?

**Comment by daminibhattacharya** [comment]
No I'm not. Its alright i guess. I don't have any genius stuff to share 😝    
  
  
  
  
  

  
  
>

**Comment by Yadhukrishnanp** [comment]
Even i don't have any.  but i guess others might share some ideas.I am doing BE at tamil nadu. trichy

**Comment by daminibhattacharya** [comment]
I don't really see any others here but yeah they might :)       
  
  
  
  
  

  
  
>

**Comment by Yadhukrishnanp** [comment]
not here. I was speaking about telegram group.I think is active.I have joined just today.

**Comment by daminibhattacharya** [comment]
Alright then. All the best to you. :)    
  
  
  
  
  

  
  
>

**Comment by Yadhukrishnanp** [comment]
All the best to you too. Nice talking with you.

**Comment by anjesh1** [comment]
Hello guy's!!

**Comment by dvigneshwer** [comment]
Hi Guys,

Feel free to join the [telegram group](https://t.me/foxIoTstudygroup) for discussion regarding different topics.
